[options]
admin_passwd = change-me-in-production
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/third-party-addons
proxy_mode = True
